branches:
  only:
    - staging
    - trying
    - master
dist: trusty
sudo: false
language: rust
matrix:
  include:
    - rust: 1.28.0
      os: linux
      env: CHECK=check FEATURES=std
    - rust: stable
      os: linux
      env: CHECK=check FEATURES=std
    - rust: beta
      os: linux
      env: CHECK=check FEATURES=std
    - rust: nightly
      os: linux
      env: CHECK=clippy FEATURES=
    - rust: nightly
      os: linux
      env: CHECK=clippy FEATURES=nightly
    - rust: nightly
      os: linux
      env: CHECK=clippy FEATURES=std
    - rust: nightly
      os: linux
      env: CHECK=clippy FEATURES=nightly std
    - rust: 1.28.0
      os: osx
      env: CHECK=check FEATURES=std
    - rust: stable
      os: osx
      env: CHECK=check FEATURES=std
    - rust: beta
      os: osx
      env: CHECK=check FEATURES=std
    - rust: nightly
      os: osx
      env: CHECK=clippy FEATURES=
    - rust: nightly
      os: osx
      env: CHECK=clippy FEATURES=nightly
    - rust: nightly
      os: osx
      env: CHECK=clippy FEATURES=std
    - rust: nightly
      os: osx
      env: CHECK=clippy FEATURES=nightly std
  allow_failures:
    - rust: beta
    - rust: nightly
install:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then rustup component add clippy-preview; fi
  - rustup component add rustfmt-preview
  - cargo fmt -v --version
script:
  - cargo $CHECK -vv --tests --no-default-features --features "$FEATURES"
  - cargo doc -vv --no-default-features --features "$FEATURES"
  - cargo test -vv --no-default-features --features "$FEATURES"
  - cargo fmt -- --check -v
