branches:
  only:
    - staging
    - trying
    - master
dist: trusty
sudo: false
os:
  - linux
  - osx
language: rust
rust:
  - 1.28.0
  - stable
  - beta
  - nightly
env:
  - CHECK=check FEATURES=std
  - CHECK=clippy FEATURES=
  - CHECK=clippy FEATURES=coerce-unsized
  - CHECK=clippy FEATURES=std
  - CHECK=clippy FEATURES=coerce-unsized std
matrix:
  exclude:
    - rust: 1.28.0
      env:
        - CHECK=clippy FEATURES=
        - CHECK=clippy FEATURES=coerce-unsized
        - CHECK=clippy FEATURES=std
        - CHECK=clippy FEATURES=coerce-unsized std
    - rust: stable
      env:
        - CHECK=clippy FEATURES=
        - CHECK=clippy FEATURES=coerce-unsized
        - CHECK=clippy FEATURES=std
        - CHECK=clippy FEATURES=coerce-unsized std
    - rust: beta
      env:
        - CHECK=clippy FEATURES=
        - CHECK=clippy FEATURES=coerce-unsized
        - CHECK=clippy FEATURES=std
        - CHECK=clippy FEATURES=coerce-unsized std
    - rust: nightly
      env: CHECK=check FEATURES=std
  allow_failures:
    - rust: beta
    - rust: nightly
install:
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then rustup component add clippy-preview; fi
  - rustup component add rustfmt-preview
  - cargo fmt -v --version
script:
  - cargo $CHECK --tests -vv --no-default-features --features "$FEATURES"
  - cargo doc -vv
  - cargo test -vv
  - cargo fmt -- --check -v
