branches:
  only:
    - staging
    - trying
    - master
environment:
  matrix:
    - CHANNEL: 1.28.0
      CHECK: check
      FEATURES: std
    - CHANNEL: stable
      CHECK: check
      FEATURES: std
    - CHANNEL: beta
      CHECK: check
      FEATURES: std
    - CHANNEL: nightly
      CHECK: clippy
      FEATURES:
    - CHANNEL: nightly
      CHECK: clippy
      FEATURES: nightly
    - CHANNEL: nightly
      CHECK: clippy
      FEATURES: std
    - CHANNEL: nightly
      CHECK: clippy
      FEATURES: nightly std
matrix:
  allow_failures:
    - CHANNEL: beta
    - CHANNEL: nightly
install:
  - SET PATH=%USERPROFILE%\.cargo\bin;%PATH%
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe"
  - rustup-init.exe -y --no-modify-path --default-host x86_64-pc-windows-msvc --default-toolchain %CHANNEL%
  - rustup component add rustfmt-preview
  - IF "%CHANNEL%"=="nightly" rustup component add clippy-preview && cargo clippy -V
  - rustup -vV
  - rustc -vV
  - cargo -vV
  - cargo fmt -v --version
build_script:
  - cargo %CHECK% -vv --tests --no-default-features --features "%FEATURES%"
  - cargo doc -vv --no-default-features --features "%FEATURES%"
test_script:
  - cargo test -vv --no-default-features --features "%FEATURES%"
  - cargo fmt -- --check -v
